// src/components/StatusBar.vue
<script setup lang="ts">
import LicenseStatus from './status-bar/LicenseStatus.vue'
import { useAppStore } from '../stores/appStore';

const { openNewEmail } = useAppStore()
</script>

<template>
  <div className="bg-neutral-200 px-3 py-1 text-xs text-gray-700 flex items-center justify-between font-mono">
    <!-- quick setting -->
    <div>
      <!-- open new email setting -->
      <div class="flex items-center gap-1">
        <span class="">Open new email</span>
        <label class="relative inline-flex items-center cursor-pointer">
          <input type="checkbox" v-model="openNewEmail" class="sr-only peer">
          <div class="w-8 h-4 bg-gray-300 peer-focus:outline-none peer-focus:ring-4 rounded-full peer
            after:content-[''] after:absolute after:bg-white after:border-white after:rounded-full after:h-4 after:w-4 after:transition-all
            peer-checked:bg-yellow-400 peer-checked:after:translate-x-full">
          </div>
        </label>
      </div>
    </div>

    <!-- license status -->
    <LicenseStatus />
  </div>
</template>

// src-react/components/StatusBar.tsx
import { ChangeEvent, useState } from "react";
import useStore from "../store";
import CheckIcon from "./icons/CheckIcon";
import XIcon from "./icons/XIcon";
import LicenseStatus from "./LicenseStatus";

export default function StatusBar() {
    const [autoOpenNewEmail, setAutoOpenNewEmai] = useStore((state) => [
        state.autoOpenNewEmail,
        state.setAutoOpenNewEmail,
    ]);
    const [validLicense, setValidLicense] = useState(false)

    return (
        <div className="bg-gray-300 px-3 text-xs text-gray-700 flex items-center justify-between">
            <Checkbox
                id="status-bar-auto-open-email-checkbox" // lol
                label="Auto open new email"
                defaultChecked={autoOpenNewEmail}
                onChange={(e: ChangeEvent<HTMLInputElement>) => {
                    setAutoOpenNewEmai(e.target.checked);
                }}
            />

            <LicenseStatus />
        </div>
    );
}

type CheckboxProps = {
    id: string;
    label: string;
    defaultChecked: boolean;
    onChange: (event: ChangeEvent<HTMLInputElement>) => void;
};

function Checkbox({ label, defaultChecked, id, onChange }: CheckboxProps) {
    return (
        <div className="inline-block px-1 hover:bg-white/50 rounded-xs">
            <label htmlFor={id}>
                {label}:
                {defaultChecked ? (
                    <CheckIcon className="inline w-5 h-5 text-green-500" />
                ) : (
                    <XIcon className="inline w-5 h-5 text-gray-500" />
                )}
            </label>
            <input className="hidden" type="checkbox" id={id} defaultChecked={defaultChecked} onChange={onChange} />
        </div >
    );
}
